# Generated by Django 5.0.4 on 2024-07-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_employee_delete_employe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('client_Name', models.CharField(max_length=100)),
                ('Date_Of_Birth', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Address', models.TextField()),
            ],
        ),
    ]
