# Generated by Django 5.0.4 on 2024-07-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
                ('operation_date', models.DateField()),
                ('observation', models.TextField()),
                ('piece_jointe', models.FileField(upload_to='piece_jointe/')),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
