# Generated by Django 5.0.4 on 2024-07-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0005_client_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
    ]
