# Generated by Django 5.0.4 on 2024-07-14 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0006_remove_client_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
